services:
  - type: web
    name: anindya-portfolio-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node cms-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
